Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/SpaceBeforeFirstArg:
  Enabled: true

Metrics/BlockNesting:
  Max: 2

Style/AlignHash:
  EnforcedColonStyle: 'key'
  EnforcedHashRocketStyle: 'key'

Style/WordArray:
  MinSize: 3

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Style/StringLiterals:
  EnforcedStyle: double_quotes
